language: node_js
node_js: "stable"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - npm install -g gulp
before_script: 
  - gulp build
