language: node_js
node_js: "stable"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - npm install -g gulp
before_script: 
  - npm install -g istanbul 
  - npm install -g mocha
  - gulp build
script: 
  - npm run-script test-travis
after_script: 
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js